### ISSUE TITLE
[nuxt] [request error] [unhandled] [500] [GET] "http://localhost:8000/api/user": <no response> fetch failed

### ISSUE THREAD

**Issue by sondh0127** [amrnn90/breeze-nuxt#18] opened 2023-11-19 02:11 UTC
![image](https://github.com/amrnn90/breeze-nuxt/assets/62163604/ec4b6894-04ad-4b8b-a1c9-16af2f441ac1)
Fresh install.
throw error on server cause issue (@amrnn90 what is the purpose of throw error here. thanks)
![image](https://github.com/amrnn90/breeze-nuxt/assets/62163604/900d3c0d-7ef9-4d69-a24c-8b95f2f26fdf)
![image](https://github.com/amrnn90/breeze-nuxt/assets/62163604/2df4cb05-dd04-4a26-b010-c35d08f7c14c)

**Comment by amrnn90** [comment] 2023-11-19 02:22
Duplicate of #3 
Update your Node.js version.

**Closed by amrnn90** 2023-11-19 02:22 UTC
